### PR TITLE
Update restricted aircraft IDs

### PR DESCRIPTION
**Pull request by aBoredDev**
Fixes the issue where the F-16 would lose all thrust and lift and go into a nosedive.

Likely caused by a change in the aircraft IDs, as the F-16 is now 7, which was previously the MD-11

### CODE REVIEW

**Comment by Qantas94Heavy** [comment]
Hey there, thanks for the great changes! If you could change the changelog to put the two changes as 0.12.0 and squash the commits down I'm happy to merge.

**Comment by aBoredDev** [comment]
I _think_ that's what you wanted me to do.  I'm not entirely sure, because I've never done this before.

**Comment by aBoredDev** [comment]
@Qantas94Heavy Hey, so you mentioned merging this after I squashed the commits.  I'm fairly certain I can't squash the commits myself, I think you have to do that when you merge, but I've done what I can, and updated the airport data one more time.

Could you kindly merge it? :)

**Review by nicolas377 — APPROVED** [review]
Looks good over here! We've merged this into the GeoFS Autoland version (hasn't been published to CWS yet, probably a 3.1 thing)

**Pull request merged**
